--
-- PostgreSQL database dump
--

-- Dumped from database version 11.8
-- Dumped by pg_dump version 11.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: xkom_task; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA xkom_task;


ALTER SCHEMA xkom_task OWNER TO postgres;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: meetings; Type: TABLE; Schema: xkom_task; Owner: postgres
--

CREATE TABLE xkom_task.meetings (
    id_meeting bigint NOT NULL,
    users_limit integer NOT NULL
)
WITH (autovacuum_enabled='true');


ALTER TABLE xkom_task.meetings OWNER TO postgres;

--
-- Name: meetings_id_meeting_seq; Type: SEQUENCE; Schema: xkom_task; Owner: postgres
--

ALTER TABLE xkom_task.meetings ALTER COLUMN id_meeting ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME xkom_task.meetings_id_meeting_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: xkom_task; Owner: postgres
--

CREATE TABLE xkom_task.users (
    id_user bigint NOT NULL,
    firstname character varying(20) NOT NULL,
    email character varying(40) NOT NULL
)
WITH (autovacuum_enabled='true');


ALTER TABLE xkom_task.users OWNER TO postgres;

--
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: xkom_task; Owner: postgres
--

ALTER TABLE xkom_task.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME xkom_task.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_meetings; Type: TABLE; Schema: xkom_task; Owner: postgres
--

CREATE TABLE xkom_task.users_meetings (
    id_user bigint NOT NULL,
    id_meeting bigint NOT NULL
)
WITH (autovacuum_enabled='true');


ALTER TABLE xkom_task.users_meetings OWNER TO postgres;

--
-- Name: meetings PK_meetings; Type: CONSTRAINT; Schema: xkom_task; Owner: postgres
--

ALTER TABLE ONLY xkom_task.meetings
    ADD CONSTRAINT "PK_meetings" PRIMARY KEY (id_meeting);


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: xkom_task; Owner: postgres
--

ALTER TABLE ONLY xkom_task.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (id_user);


--
-- Name: users_meetings PK_users_meetings; Type: CONSTRAINT; Schema: xkom_task; Owner: postgres
--

ALTER TABLE ONLY xkom_task.users_meetings
    ADD CONSTRAINT "PK_users_meetings" PRIMARY KEY (id_user, id_meeting);


--
-- Name: users_meetings Sings up for a meeting; Type: FK CONSTRAINT; Schema: xkom_task; Owner: postgres
--

ALTER TABLE ONLY xkom_task.users_meetings
    ADD CONSTRAINT "Sings up for a meeting" FOREIGN KEY (id_user) REFERENCES xkom_task.users(id_user);


--
-- Name: users_meetings adds user to the meeting; Type: FK CONSTRAINT; Schema: xkom_task; Owner: postgres
--

ALTER TABLE ONLY xkom_task.users_meetings
    ADD CONSTRAINT "adds user to the meeting" FOREIGN KEY (id_meeting) REFERENCES xkom_task.meetings(id_meeting);


--
-- PostgreSQL database dump complete
--

